all:
	gcc -o client/client/client.exe client/client/client.c
	gcc -o client/client1/client1.exe client/client1/client1.c
	gcc -o client/client2/client2.exe client/client2/client2.c
	gcc -o client/client3/client3.exe client/client3/client3.c
	gcc -o client/client4/client4.exe client/client4/client4.c
	gcc -o client/client5/client5.exe client/client5/client5.c
	gcc -o server/server.exe server/server.c -lpthread
